### ISSUE TITLE
Help please?

### ISSUE THREAD

**Issue by jackiellowery** [pclifford/borderlands2#1]
Your script is looking like a great start for modding bl2 saves.  At least the file is somewhat readable now.  But i still can't search for my money value and hex edit it.  Any ideas?

Also, there are some people starting a new version of WillowTree.  I'm sure you would make a great addition to the team if you have any spare time.  Thanks.

https://sourceforge.net/projects/willowtree/forums/forum/1117810/topic/5874406/index/page/3

**Comment by pclifford** [comment]
You can add -p 6:0 to unpack the field containing money and eridium.  Or I just added an option to make simple changes directly, see the updated README file for an example.
