### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by Htgan** [pclifford/borderlands2#2]
Hey, sorry about being a very stupid person.

After typing :

sudo python ./savefile.py -m
skillpoints=99,money=9999999,eridium=99,itemlevels <SAVE0001.SAV>
SAVE0002.SAV

I get:

Traceback (most recent call last):
  File "./savefile.py", line 396, in <module>
    main()
  File "./savefile.py", line 376, in main
    k, v = m.split("=", 1)
ValueError: need more than 1 value to unpack

Have I missed a step?

I've never touched linux and python before today and I have set up everything from the ground up installing ubuntu and getting python and binding it with lzo. This seems to be the final step for me and I have 0 knowledge to help me figure this one out. Please be so kind to give me a hand.

**Comment by Htgan** [comment]
I have added =31 after itemlevels, thinking that if I set multiple information at the same time I should also give "itemlevels" a value like the rest of them. What happens now is:

```
Traceback (most recent call last):
```

  File "./savefile.py", line 396, in <module>
    main()
  File "./savefile.py", line 378, in main
    output.write(modify_save(input.read(), changes, endian))
  File "./savefile.py", line 290, in modify_save
    player = read_protobuf(unwrap_player_data(data))
  File "./savefile.py", line 248, in unwrap_player_data

```
raise BL2Error("Invalid save file")
```

**main**.BL2Error: Invalid save file

Just to confirm, so that I don't look even more stupid.  Does this work with PS3 save files??

**Comment by pclifford** [comment]
You're following instructions for the newest version but using an older version of the savefile.py script (the error shows something different for line 376 than what is currently there: https://github.com/pclifford/borderlands2/blob/master/savefile.py#L376).  Grab the latest version of savefile.py first.

Looking just at the filename (so I might be wrong) you probably also haven't extracted the Borderlands 2 save data from inside the console container.  If it came from an Xbox you'll need to use something like Horizon or Modio to extract the SaveGame.sav file inside, assuming you're a Windows user.  If it came from a PS3, I'm not sure what the right tool to use is, but I'm sure there's an equivalent.

If you get the above fixed, the command you're using will print the result to stdout which means you'll get a screenful of odd looking characters.  You should add an extra filename on the end, telling the script where to write the data instead of printing it to the screen; something like:

```
./savefile.py -m whatever OldSaveGame.sav NewSaveGame.sav
```

**Comment by Htgan** [comment]
Thank you for the quick reply,

I had my oldsavegame.sav in brackets in the first post, which somehow caused it to disappear.

I have tried again with the new savefile.py and I still get:

sudo python ./savefile.py -m skillpoints=99 SAVE0001.SAV SAVE0002.SAV

Traceback (most recent call last):
  File "./savefile.py", line 487, in module (there were brackets around "module" I removed them so they don't disappear)
    main()
  File "./savefile.py", line 469, in main
    output.write(modify_save(input.read(), changes, endian))
  File "./savefile.py", line 368, in modify_save
    player = read_protobuf(unwrap_player_data(data))
  File "./savefile.py", line 326, in unwrap_player_data
    raise BL2Error("Invalid save file")
**main**.BL2Error: Invalid save file

So I guess you are right about extracting the save file? What I did was I plugged a USB onto the PS3 and copy'n'pasted the game save file to the USB. Then I pluged it onto my laptop. I'm trying to find things like Modio for PS3 but I don't really have any key words, because I don't really know what they are. A hand with it?
Thanks so much for replying so quickly in detail by the way, I really appreciate it. And I cannot even begin to appreciate this complex thing you've written.

**Comment by pclifford** [comment]
It looks like the PS3 provides optional support for encrypting game save files (in addition to any encryption or obfuscation performed by the game itself), and it's down to individual game developers whether or not they use this for a particular title.  Borderlands 1 apparently didn't, but Borderlands 2 does.  There's a bit more information at http://www.ps3devwiki.com/wiki/Game_Saves and http://www.ps3devwiki.com/wiki/PARAM.PFD but from what I can see there are still too many unknowns for someone to be able to write something to access the raw data inside these encrypted save files.

**Comment by Htgan** [comment]
You are AWESOME. That is precisely everything I needed to hear. Although I wasn't able to modify my save, I still feel pretty acomplished doing all the research and learning from zero. I'll hang around your page from now on. I know you've got good stuff.

**Comment by y-me-y** [comment]
Hopefully this is an ok place to follow up, this is what I got

C:\Python26>savefile.py -m skillpoints=99,eridium=99 Save0001.sav Save0002.sav
Traceback (most recent call last):
  File "C:\Python26\savefile.py", line 478, in <module>
    main()
  File "C:\Python26\savefile.py", line 460, in main
    output.write(modify_save(input.read(), changes, endian))
  File "C:\Python26\savefile.py", line 359, in modify_save
    player = read_protobuf(unwrap_player_data(data))
  File "C:\Python26\savefile.py", line 317, in unwrap_player_data
    raise BL2Error("Invalid save file")
**main**.BL2Error: Invalid save file

I did install python on windows if this is just as simple as running it on linux let me know. I was just working with what I had available.

**Comment by jackiellowery** [comment]
Sounds like you haven't extracted the actual GameSave.sav file using a tool like modio.

**Comment by y-me-y** [comment]
i'd simply like to sa y d'oh. Thanks for the quick response....sorry I had to ask.

**Comment by jackiellowery** [comment]
Hi pclifford,

If i provide you with a PS3 gamesave, is there a chance you could modify the script to edit it?

**Comment by homer357** [comment]
hi clifford 

how can i increase my inventory and skill points on ps3 i loved bl1 & WT coz it was so simple (like me) but im dying to be able 2 carry more, got a lot of lvl 50 rares on ps3 if anyone wants any!

**Comment by pclifford** [comment]
See my earlier comment: the PS3 apparently provides optional support for encrypting game save files, on top of any compression and encryption performed by the game itself.  Apparently this wasn't used for Borderlands 1 but it is for Borderlands 2, and from what I could see on the ps3devwiki site it's not currently possible to get around this -- for any game that uses this feature, not just for Borderlands 2.

I could be wrong -- I don't have a PS3 and haven't looked into this in any particular detail -- but if it was possible I'd expect there to be something broadly similar to Modio or Horizon for extracting and inserting data from PS3 game saves.  If you can find such a program (and I didn't see anything obvious after a few Google searches), presumably the extracted save file would work with this script (or other programs) in the same way as a PC or Xbox save file.
