### ISSUE TITLE
Saving Player.json back to SaveGame.sav

### ISSUE THREAD

**Issue by Wra** [pclifford/borderlands2#5]
C:\BL2>python savefile.py -d -j -p savegame.sav player.json

C:\BL2>python savefile.py -j player.json savegamemodded.sav
Something went wrong, but please ensure you have the latest version from https:/
/github.com/pclifford/borderlands2 before reporting a bug.  Information useful f
or a report follows:
['savefile.py', '-j', 'player.json', 'savegamemodded.sav']
Traceback (most recent call last):
  File "savefile.py", line 1006, in <module>
    main()
  File "savefile.py", line 1000, in main
    player = write_protobuf(data)
  File "savefile.py", line 293, in write_protobuf
    write_protobuf_value(sub_b, wire_type, v)
  File "savefile.py", line 310, in write_protobuf_value
    write_varint(b, len(value))
TypeError: object of type 'int' has no len()

The only thing I have edited is the ammo in the backpack.

**Comment by pclifford** [comment]
Are you talking about the entries under the "resources" key?  Like this:

```
{   
    "amount": 30.0,
    "level": 0,
    "pool": "D_Resourcepools.AmmoPools.Ammo_Combat_Rifle_Pool",
    "resource": "D_Resources.AmmoResources.Ammo_Combat_Rifle"
}
```

I've tried changing all those number and I can't reproduce the problem.  Can you put your JSON file somewhere where I can take a look at it?

**Comment by jdaiv** [comment]
I also have the same issue, although I haven't edited anything in the save. The same error is produced on both parsed and un-parsed JSON.

Edit:
Here's the JSON file: http://pastebin.com/zEGHU2Zu

**Comment by pclifford** [comment]
Thanks, I think I've found and fixed the problem.  Can you try again with the latest version?

**Comment by jdaiv** [comment]
Tried the latest version, seems to be all good. Save file loads in PC version of the game when converted back.

At first I thought the rewritten save file would be corrupted as it was 8 KB bigger, but the loading the save brings the size back down to the original size.

**Comment by pclifford** [comment]
LZO, the compression algorithm used for the outermost part of the save files, has a number of variants and the one I ended up embedding in the Python code appears to trade some file size for more speed. On the other hand if you change it back to using the C code LZO implementation the default variant used there makes the file smaller than the original. Either way it doesn't seem to affect the usability of the save files and, as you note, once it has been saved back out from the game the difference goes away.
