### ISSUE TITLE
Weapon Data Structure

### ISSUE THREAD

**Issue by jdaiv** [pclifford/borderlands2#6]
(Not an issue as such, just don't know where else to ask!)

I've noticed you've made some work on deconstructing weapon data. I've been poking around but found nothing, mostly because I have no clue what I'm doing.

Have you made any progress on working out what's what in that big array of item data?

**Comment by pclifford** [comment]
I understand enough about the structure of the items to create and modify them, but I think it'll be disappointing for anyone looking to replicate the crazy custom weapons that were apparently possible in Borderlands 1.

There is a large set of templates for weapons, shields, grenade mods, etc, each with their own lists of customisable parts and you can only create or modify something within those bounds.  For example, the Vault Hunter's Relic (5% higher chance of rare loot) has no options for variations at all, while the Infinity Pistol can be assigned different sorts of elemental damage but has a fixed barrel, and so on.

You can adjust an existing item to "perfect" it, by adding optional properties that the random number generator left out, or by doing something like switching fire damage for corrosive, but it's a fairly boring process that I haven't found much enthusiasm for yet -- I'm still slowly working my way through the first playthrough enjoying the weird and wacky items the game naturally throws at you.

Are you looking to achieve something in particular, or just curious?  I have some ideas for user interfaces to streamline the process of creating and modifying these things, but I wasn't planning to explore them for a while.

**Comment by jrudder** [comment]
I've created a quick-and-dirty curses interface that breaks down the weapon and item data into component parts. You can check it out here: https://github.com/ninjawhipitmaster/b2ec.

pclifford -- I've included the (as of now) current version of your savefile.py in the repository. If you'd prefer, I will remove it and direct users to download it directly from your repository.  Also, I've messed around a bit by tweaking weapons and also by trying to create various Unique and Legendary weapons from scratch but without any luck. Do you know if there is some trick to choosing compatible options?
