### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by davidyell** [pclifford/borderlands2#7]
Hi,
I'm running this on a Mac using Python v2.7.2

```
ukwm157:76561197971413131 david$ pwd
/Users/david/Library/Application Support/Borderlands 2/WillowGame/SaveData/76561197971413131
ukwm157:76561197971413131 david$ python /Users/david/Sites/borderlands2/savefile.py -m money=100000 Save0001.sav Save0002.sav 
Something went wrong, but please ensure you have the latest version from https://github.com/pclifford/borderlands2 before reporting a bug.  Information useful for a report follows:
['/Users/david/Sites/borderlands2/savefile.py', '-m', 'money=100000', 'Save0001.sav', 'Save0002.sav']
Traceback (most recent call last):
  File "/Users/david/Sites/borderlands2/savefile.py", line 1128, in <module>
    main(options, args)
  File "/Users/david/Sites/borderlands2/savefile.py", line 1099, in main
    output.write(modify_save(input.read(), changes, endian))
  File "/Users/david/Sites/borderlands2/savefile.py", line 891, in modify_save
    player = read_protobuf(unwrap_player_data(data))
  File "/Users/david/Sites/borderlands2/savefile.py", line 623, in unwrap_player_data
    raise BL2Error("Invalid save file")
__main__.BL2Error: Invalid save file
ukwm157:76561197971413131 david$ 
```

**Comment by pclifford** [comment]
That's odd, from what I can see elsewhere the file format is supposed to be the same on the PC and Mac versions but that error suggests they're different in some way.  Can you upload one of the save files that's causing you problems somewhere, so I can take a look at it?

**Comment by davidyell** [comment]
I've zipped all my savegame files to here, https://dl.dropbox.com/u/16573285/BL2-WorkMac-save.zip

It should be a lv6 Gunzerker if memory serves.

I'll make another new character at lunchtime and see if it's just a bad savegame. I might have accidentally tarballed the file into its-self, but the game still loads it fine.

**Comment by davidyell** [comment]
Apologies, I've checked in the game load, and I see two new saves listed as `!Corrupted!`

**Comment by pclifford** [comment]
Save0001.sav appears to be a bzip2'd tarball (try "tar tvjf Save0001.sav") containing the Save0001.sav.bak and profile.bin files under a "76561197971413131" directory.

Save0001.sav.bak looks like your level 6 Gunzerker; you could try renaming/copying it to Save0001.sav to recover it.  I can read and modify this file fine with the savefile.py script.

Save0002.sav is empty, but from the original bug report I expect that's because it was created by the savefile.py run before it raised the exception.
